/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzagui;

import java.awt.Desktop;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.URI;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author kadar
 */
public class PizzaGuiFrame extends javax.swing.JFrame {

    private String jelen_szam;
    private String jelen_szoveg;
    private static int Vegosszeg;
    
    
    /**
     * Creates new form PizzaGuiFrame
     */
    public PizzaGuiFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        button_32cm = new javax.swing.JRadioButton();
        button_Torles = new javax.swing.JButton();
        button_Fitness = new javax.swing.JRadioButton();
        button_Italy = new javax.swing.JRadioButton();
        button_24cm = new javax.swing.JRadioButton();
        label_KosarbanDarab = new javax.swing.JLabel();
        checkbox_Gluten = new javax.swing.JCheckBox();
        label_PizzaTipus = new javax.swing.JLabel();
        button_45cm = new javax.swing.JRadioButton();
        combobox_PizzaTipus = new javax.swing.JComboBox<>();
        button_Classic = new javax.swing.JRadioButton();
        label_Kosarban = new javax.swing.JLabel();
        button_Kosarba = new javax.swing.JButton();
        label_Vegosszeg = new javax.swing.JLabel();
        label_VegosszegFt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_Kapcsolat = new javax.swing.JLabel();
        textfield_Cim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textfield_Telszam = new javax.swing.JTextField();
        button_Megrendel = new javax.swing.JButton();
        label_ForteKep = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_Wallpaper1 = new javax.swing.JLabel();
        label_Wallpaper2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PizzaRendelés");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rendelés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 14))); // NOI18N

        buttonGroup2.add(button_32cm);
        button_32cm.setSelected(true);
        button_32cm.setText("32 cm");

        button_Torles.setText("Eddigiek törlése");
        button_Torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TorlesActionPerformed(evt);
            }
        });

        buttonGroup1.add(button_Fitness);
        button_Fitness.setForeground(new java.awt.Color(153, 0, 102));
        button_Fitness.setText("Fitness");

        buttonGroup1.add(button_Italy);
        button_Italy.setForeground(new java.awt.Color(204, 0, 0));
        button_Italy.setText("Italy");
        button_Italy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ItalyActionPerformed(evt);
            }
        });

        buttonGroup2.add(button_24cm);
        button_24cm.setText("24 cm");

        label_KosarbanDarab.setText("0");

        checkbox_Gluten.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        checkbox_Gluten.setText("Gluténmentes");

        label_PizzaTipus.setText("Pizza típus:");

        buttonGroup2.add(button_45cm);
        button_45cm.setText("45 cm");

        combobox_PizzaTipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Válasszon -", "HÚSIMÁDÓ", "HAWAII", "MAGYAROS", "MARGHERITA", "BBQ", "CARBONARA", "ESCOBAR", "FALUSI", "MILANO", "NAPOLITANA", "NÉGYSAJTOS" }));

        buttonGroup1.add(button_Classic);
        button_Classic.setForeground(new java.awt.Color(51, 153, 0));
        button_Classic.setSelected(true);
        button_Classic.setText("Classic");

        label_Kosarban.setText("Kosárban:");

        button_Kosarba.setBackground(new java.awt.Color(0, 153, 0));
        button_Kosarba.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        button_Kosarba.setForeground(new java.awt.Color(255, 255, 255));
        button_Kosarba.setText("Kosárba");
        button_Kosarba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_KosarbaActionPerformed(evt);
            }
        });

        label_Vegosszeg.setText("Végösszeg:");

        label_VegosszegFt.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_Classic)
                            .addComponent(button_24cm))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_Italy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_32cm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_Fitness, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_45cm, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(label_PizzaTipus)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbox_Gluten)
                            .addComponent(combobox_PizzaTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_Kosarban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_KosarbanDarab, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_Torles))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(label_Vegosszeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_VegosszegFt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Kosarba)))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Classic)
                    .addComponent(button_Italy)
                    .addComponent(button_Fitness))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_24cm)
                    .addComponent(button_32cm)
                    .addComponent(button_45cm))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_PizzaTipus)
                    .addComponent(combobox_PizzaTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkbox_Gluten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_VegosszegFt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Vegosszeg))
                    .addComponent(button_Kosarba))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Kosarban)
                    .addComponent(label_KosarbanDarab)
                    .addComponent(button_Torles))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kiszállítás", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 14))); // NOI18N

        jLabel2.setText("Tel.szám:");

        label_Kapcsolat.setForeground(new java.awt.Color(0, 102, 204));
        label_Kapcsolat.setText("Kapcsolat");
        label_Kapcsolat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_KapcsolatMouseClicked(evt);
            }
        });

        textfield_Cim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_CimActionPerformed(evt);
            }
        });

        jLabel1.setText("Cím:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_Kapcsolat, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_Telszam)
                            .addComponent(textfield_Cim))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfield_Cim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfield_Telszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(label_Kapcsolat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 440));

        button_Megrendel.setBackground(new java.awt.Color(204, 0, 0));
        button_Megrendel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Megrendel.setForeground(new java.awt.Color(255, 255, 255));
        button_Megrendel.setText("Megrendel");
        button_Megrendel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MegrendelActionPerformed(evt);
            }
        });
        getContentPane().add(button_Megrendel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        label_ForteKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagui/kepek/pizzaforte_image.png"))); // NOI18N
        getContentPane().add(label_ForteKep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 2, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ahogy Te szereted!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        label_Wallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagui/kepek/wood_wallpaper.jpg"))); // NOI18N
        label_Wallpaper1.setText("jLabel4");
        getContentPane().add(label_Wallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        label_Wallpaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzagui/kepek/wood_wallpaper.jpg"))); // NOI18N
        label_Wallpaper2.setText("jLabel4");
        getContentPane().add(label_Wallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 310, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_KapcsolatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_KapcsolatMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(URI.create("https://pizzaforte.hu/assets/files/en/contactus.html"));
        } catch (IOException ex) {
            Logger.getLogger(Oldalbeallitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_label_KapcsolatMouseClicked

    private void button_KosarbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_KosarbaActionPerformed
        // TODO add your handling code here:
        String valasztott_pizza = (String) combobox_PizzaTipus.getSelectedItem();
        
        
        String print_szoveg = "";
        
        if (valasztott_pizza == "- Válasszon -") {
            print_szoveg = "Kérem válasszon ki egy pizza fajtát!";
            JOptionPane.showMessageDialog(rootPane, print_szoveg);
        } else {
            // megy tovább a kód
        }

        
        String jelen_szoveg = label_KosarbanDarab.getText();
        int jelen_szam = parseInt(jelen_szoveg) ;
        jelen_szam += 1;
        
        if (jelen_szam > 3) {
            JOptionPane.showMessageDialog(rootPane, "A maximum 3 db!");
        } else {
            // frissiti a label_K. tartalmát
            label_KosarbanDarab.setText(Integer.toString(jelen_szam));
        }
        
        
        Vegosszeg = jelen_szam * 1900;
        label_VegosszegFt.setText(Vegosszeg+" Ft");

    }//GEN-LAST:event_button_KosarbaActionPerformed

    private void button_TorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TorlesActionPerformed
        // TODO add your handling code here:
        label_KosarbanDarab.setText("0");
    }//GEN-LAST:event_button_TorlesActionPerformed

    private void button_MegrendelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MegrendelActionPerformed
        // TODO add your handling code here:
        String print_szoveg = "";
        


        String jelen_szoveg = label_KosarbanDarab.getText();
        int jelen_szam = parseInt(jelen_szoveg) ;
        
        
        String cim_szoveg = textfield_Cim.getText();
        String telszam_szoveg = textfield_Telszam.getText();
        
        String valasztott_pizza = (String) combobox_PizzaTipus.getSelectedItem();
        
        if (checkbox_Gluten.isSelected()) {
            valasztott_pizza += " Pizza (Gluténmentes)";
        } else {
            valasztott_pizza += " Pizza";
        }
        
        
        if (jelen_szam == 0) {
            print_szoveg = "0 db van a kosárban!";
        } else {
            if (cim_szoveg.length() < 7) {
                print_szoveg = "Kérlek létező címet adj meg!";
        }   else if (cim_szoveg.length() < 10) {
                print_szoveg = "Kérlek létező telefonszámot adj meg!";
        }   else
        {       print_szoveg = "Rendelés: " + valasztott_pizza + "\nVégösszeg: " + Vegosszeg + " Ft\nCím: " + cim_szoveg + "\nKiszállítási idő: 45 perc"; }
        }
        
        
        
        JOptionPane.showMessageDialog(rootPane, print_szoveg);
    }//GEN-LAST:event_button_MegrendelActionPerformed

    private void button_ItalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ItalyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_ItalyActionPerformed

    private void textfield_CimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_CimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_CimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaGuiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton button_24cm;
    private javax.swing.JRadioButton button_32cm;
    private javax.swing.JRadioButton button_45cm;
    private javax.swing.JRadioButton button_Classic;
    private javax.swing.JRadioButton button_Fitness;
    private javax.swing.JRadioButton button_Italy;
    private javax.swing.JButton button_Kosarba;
    private javax.swing.JButton button_Megrendel;
    private javax.swing.JButton button_Torles;
    private javax.swing.JCheckBox checkbox_Gluten;
    private javax.swing.JComboBox<String> combobox_PizzaTipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_ForteKep;
    private javax.swing.JLabel label_Kapcsolat;
    private javax.swing.JLabel label_Kosarban;
    private javax.swing.JLabel label_KosarbanDarab;
    private javax.swing.JLabel label_PizzaTipus;
    private javax.swing.JLabel label_Vegosszeg;
    private javax.swing.JLabel label_VegosszegFt;
    private javax.swing.JLabel label_Wallpaper1;
    private javax.swing.JLabel label_Wallpaper2;
    private javax.swing.JTextField textfield_Cim;
    private javax.swing.JTextField textfield_Telszam;
    // End of variables declaration//GEN-END:variables
}
